#!/usr/bin/env python
"""Utility to add Python scripts into an Open Grid Scheduler/Grid Engine queue.

Usage: qadd script.py -q [queuename] -n [jobname]
"""

import os
import subprocess
import argparse


TEMPLATE_SERIAL = """
#$ -cwd
#$ -N {job_name}
#$ -e {errfile}
#$ -o {logfile}
#$ -q {queue}

echo "Job started on" `date +%Y-%m-%d' '%H:%M:%S`
echo "----------------------------------"

python -u {script_name}

echo "--------------------------------"
echo "Job ended on" `date +%Y-%m-%d' '%H:%M:%S`
"""


def add_to_queue(python_file, job_name=None, cleanup=True, queue='larga'):
    """Put a Python script into an OGE queue.

    Parameters
    ----------
    python_file : str
        Script containing the code to run.
    job_name : str
        Name of the job.
    cleanup : Boolean
        Indicates to remove the temporary file.
    queue: str
        Name of the queue to append the job.
    """
    logfile = '$JOB_NAME_$JOB_ID.out'
    errfile = '$JOB_NAME_$JOB_ID.error'

    # Handle job name
    if not job_name:
        job_name = python_file[:-3]

    # Fill template
    template = TEMPLATE_SERIAL.format(
        script_name=python_file,
        job_name=job_name,
        logfile=logfile,
        errfile=errfile,
        queue=queue
    )

    # Write temporary file
    open('job.qsub', 'wb').write(template)

    # Make the call to qsub and remove temporary file
    try:
        subprocess.call('qsub < job.qsub', shell=True)
    finally:
        if cleanup:
            os.remove('job.qsub')

if __name__ == '__main__':
    # Parse arguments
    description = 'Adds Python script to OGE queue.'
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('script', help='Script name')
    parser.add_argument('-q', '--queue', default='larga', help='Queue')
    parser.add_argument('-n', '--name', default='', help='Job Name')

    # Parse arguments
    args = parser.parse_args()

    # Send code with queue and name
    add_to_queue(args.script, queue=args.queue, job_name=args.name)
